# Generated by Django 3.2.2 on 2021-05-09 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldatabase',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Tells the particular user is linked to which registered USER -> whose CONTACT is this person.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
