# Generated by Django 3.2.2 on 2021-05-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_globaldatabase_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldatabase',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the person.', max_length=100, null=True, verbose_name='full name'),
        ),
    ]
